apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment.properties
  namespace: staging
data:
  environment.properties: |
    env=staging
