kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster-fs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
